
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package menwic.interprete.txtprueba;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 4;
  public static final int MENOR = 9;
  public static final int NumEntero = 20;
  public static final int IGUAL = 2;
  public static final int LEER = 25;
  public static final int FIN_CASO = 30;
  public static final int ERROR = 34;
  public static final int PAR_C = 11;
  public static final int EN_CASO_DE = 28;
  public static final int PAR_A = 10;
  public static final int DEPLANO = 31;
  public static final int FLOTANTE = 18;
  public static final int PARA = 32;
  public static final int POR = 5;
  public static final int DOS_PUNTOS = 16;
  public static final int CASO = 29;
  public static final int COMA = 14;
  public static final int Cadena = 23;
  public static final int MAYOR = 8;
  public static final int EOF = 0;
  public static final int SINO = 27;
  public static final int DIV = 6;
  public static final int SI = 26;
  public static final int ESCRIBIR = 24;
  public static final int TEXTO = 19;
  public static final int error = 1;
  public static final int LLAVE_C = 13;
  public static final int NumDecimal = 21;
  public static final int LLAVE_A = 12;
  public static final int PUNTO_COMA = 15;
  public static final int NomVariable = 22;
  public static final int ENTERO = 17;
  public static final int MIENTRAS = 33;
  public static final int MAS = 3;
  public static final int DIF = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IGUAL",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "DIF",
  "MAYOR",
  "MENOR",
  "PAR_A",
  "PAR_C",
  "LLAVE_A",
  "LLAVE_C",
  "COMA",
  "PUNTO_COMA",
  "DOS_PUNTOS",
  "ENTERO",
  "FLOTANTE",
  "TEXTO",
  "NumEntero",
  "NumDecimal",
  "NomVariable",
  "Cadena",
  "ESCRIBIR",
  "LEER",
  "SI",
  "SINO",
  "EN_CASO_DE",
  "CASO",
  "FIN_CASO",
  "DEPLANO",
  "PARA",
  "MIENTRAS",
  "ERROR"
  };
}

