
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package menwic.interprete.analizadores.a_sintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 5;
  public static final int MENOR = 10;
  public static final int GUION_B = 11;
  public static final int NumEntero = 23;
  public static final int IGUAL = 3;
  public static final int LETRA = 19;
  public static final int LEER = 28;
  public static final int ERROR = 32;
  public static final int PAR_C = 13;
  public static final int PAR_A = 12;
  public static final int FLOTANTE = 21;
  public static final int PARA = 31;
  public static final int POR = 6;
  public static final int COMA = 15;
  public static final int Cadena = 26;
  public static final int MAYOR = 9;
  public static final int EOF = 0;
  public static final int Token = 2;
  public static final int SINO = 30;
  public static final int DIV = 7;
  public static final int TERM_LINEA = 17;
  public static final int COMILLA = 14;
  public static final int SI = 29;
  public static final int ESCRIBIR = 27;
  public static final int TEXTO = 22;
  public static final int ESPACIO_BLANCO = 18;
  public static final int error = 1;
  public static final int NumDecimal = 24;
  public static final int PUNTO_COMA = 16;
  public static final int NomVariable = 25;
  public static final int ENTERO = 20;
  public static final int MAS = 4;
  public static final int DIF = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Token",
  "IGUAL",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "DIF",
  "MAYOR",
  "MENOR",
  "GUION_B",
  "PAR_A",
  "PAR_C",
  "COMILLA",
  "COMA",
  "PUNTO_COMA",
  "TERM_LINEA",
  "ESPACIO_BLANCO",
  "LETRA",
  "ENTERO",
  "FLOTANTE",
  "TEXTO",
  "NumEntero",
  "NumDecimal",
  "NomVariable",
  "Cadena",
  "ESCRIBIR",
  "LEER",
  "SI",
  "SINO",
  "PARA",
  "ERROR"
  };
}

